# Generated by Django 5.2.1 on 2026-03-15 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=150, verbose_name='título')),
                ('subject', models.CharField(choices=[('matematica', 'Matemática'), ('portugues', 'Português'), ('biologia', 'Biologia'), ('fisica', 'Física'), ('quimica', 'Química'), ('historia', 'História'), ('geografia', 'Geografia'), ('ingles', 'Inglês'), ('outra', 'Outra')], default='matematica', max_length=20, verbose_name='disciplina')),
                ('application_date', models.DateField(verbose_name='data da aplicação')),
                ('question_count', models.PositiveIntegerField(verbose_name='quantidade de questões')),
                ('max_score', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='nota máxima')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='schools.classgroup', verbose_name='turma')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'prova',
                'verbose_name_plural': 'provas',
                'ordering': ['-application_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StudentExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('total_correct', models.PositiveIntegerField(default=0, verbose_name='total de acertos')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='nota')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='percentual')),
                ('corrected_at', models.DateTimeField(blank=True, null=True, verbose_name='corrigido em')),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrected_results', to=settings.AUTH_USER_MODEL, verbose_name='corrigido por')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.exam', verbose_name='prova')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='schools.student', verbose_name='aluno')),
            ],
            options={
                'verbose_name': 'resultado da prova',
                'verbose_name_plural': 'resultados das provas',
                'ordering': ['student__name'],
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='AnswerKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('question_number', models.PositiveIntegerField(verbose_name='número da questão')),
                ('correct_alternative', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, verbose_name='alternativa correta')),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='peso')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_keys', to='exams.exam', verbose_name='prova')),
            ],
            options={
                'verbose_name': 'gabarito',
                'verbose_name_plural': 'gabaritos',
                'ordering': ['question_number'],
                'unique_together': {('exam', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('question_number', models.PositiveIntegerField(verbose_name='número da questão')),
                ('is_correct', models.BooleanField(default=False, verbose_name='acertou')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.studentexamresult', verbose_name='resultado')),
            ],
            options={
                'verbose_name': 'resposta do aluno',
                'verbose_name_plural': 'respostas dos alunos',
                'ordering': ['question_number'],
                'unique_together': {('result', 'question_number')},
            },
        ),
    ]
