# Generated by Django 5.2.1 on 2026-03-16 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='class_group',
        ),
        migrations.CreateModel(
            name='ExamApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_applications', to='schools.classgroup', verbose_name='turma')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='exams.exam', verbose_name='prova')),
            ],
            options={
                'verbose_name': 'aplicação da prova',
                'verbose_name_plural': 'aplicações da prova',
                'ordering': ['class_group__school_year', 'class_group__grade_level', 'class_group__name'],
                'unique_together': {('exam', 'class_group')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='studentexamresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentexamresult',
            name='exam_application',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.examapplication', verbose_name='aplicação da prova'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='studentexamresult',
            unique_together={('exam_application', 'student')},
        ),
        migrations.DeleteModel(
            name='AnswerKey',
        ),
        migrations.RemoveField(
            model_name='studentexamresult',
            name='exam',
        ),
    ]
