# Generated by Django 5.2.1 on 2026-03-15 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='estado')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'escola',
                'verbose_name_plural': 'escolas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=50, verbose_name='nome da turma')),
                ('grade_level', models.CharField(choices=[('1EM', '1º ano do Ensino Médio'), ('2EM', '2º ano do Ensino Médio'), ('3EM', '3º ano do Ensino Médio')], max_length=3, verbose_name='série/ano')),
                ('shift', models.CharField(choices=[('matutino', 'Matutino'), ('vespertino', 'Vespertino'), ('noturno', 'Noturno'), ('integral', 'Integral')], max_length=20, verbose_name='turno')),
                ('school_year', models.PositiveIntegerField(verbose_name='ano letivo')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('responsible_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_classes', to=settings.AUTH_USER_MODEL, verbose_name='professor responsável')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='schools.school', verbose_name='escola')),
            ],
            options={
                'verbose_name': 'turma',
                'verbose_name_plural': 'turmas',
                'ordering': ['-school_year', 'grade_level', 'name'],
                'unique_together': {('school', 'name', 'school_year')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('registration_number', models.CharField(blank=True, max_length=50, verbose_name='matrícula')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.classgroup', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'aluno',
                'verbose_name_plural': 'alunos',
                'ordering': ['name'],
                'unique_together': {('class_group', 'name')},
            },
        ),
    ]
